export const useTranslationService = () => {
  const signedLanguages = [
    'ase', 'gsg', 'fsl', 'bfi', 'ils', 'sgg', 'ssr', 'slf', 'ssp', 'jos', 'rsl-by', 'bqn', 'csl', 
    'csq', 'cse', 'dsl', 'ins', 'nzs', 'eso', 'fse', 'asq', 'gss-cy', 'gss', 'icl', 'ise', 'jsl', 
    'lsl', 'lls', 'psc', 'pso', 'bzs', 'psr', 'rms', 'rsl', 'svk', 'aed', 'csg', 'csf', 'mfs', 
    'swl', 'tsm', 'ukl', 'pks',
  ];

//   const spokenLanguages = [
//     'en', 'de', 'fr', 'af', 'sq', 'am', 'ar', 'hy', 'az', 'eu', 'be', 'bn', 'bs', 'bg', 'ca',
//     'ceb', 'ny', 'zh', 'co', 'hr', 'cs', 'da', 'nl', 'eo', 'et', 'tl', 'fi', 'fy', 'gl', 'ka',
//     'es', 'el', 'gu', 'ht', 'ha', 'haw', 'he', 'hi', 'hmn', 'hu', 'is', 'ig', 'id', 'ga', 'it',
//     'ja', 'jv', 'kn', 'kk', 'km', 'rw', 'ko', 'ku', 'ky', 'lo', 'la', 'lv', 'lt', 'lb', 'mk',
//     'mg', 'ms', 'ml', 'mt', 'mi', 'mr', 'mn', 'my', 'ne', 'no', 'or', 'ps', 'fa', 'pl', 'pt',
//     'pa', 'ro', 'ru', 'sm', 'gd', 'sr', 'st', 'sn', 'sd', 'si', 'sk', 'sl', 'so', 'su', 'sw',
//     'sv', 'tg', 'ta', 'tt', 'te', 'th', 'tr', 'tk', 'uk', 'ur', 'ug', 'uz', 'vi', 'cy', 'xh',
//     'yi', 'yo', 'zu',
	//   ];
	const spokenLanguages = {
		en: "English",
		de: "German",
		fr: "French",
		af: "Afrikaans",
		sq: "Albanian",
		am: "Amharic",
		ar: "Arabic",
		hy: "Armenian",
		az: "Azerbaijani",
		eu: "Basque",
		be: "Belarusian",
		bn: "Bengali",
		bs: "Bosnian",
		bg: "Bulgarian",
		ca: "Catalan",
		ceb: "Cebuano",
		ny: "Chichewa",
		zh: "Chinese",
		co: "Corsican",
		hr: "Croatian",
		cs: "Czech",
		da: "Danish",
		nl: "Dutch",
		eo: "Esperanto",
		et: "Estonian",
		tl: "Filipino",
		fi: "Finnish",
		fy: "Frisian",
		gl: "Galician",
		ka: "Georgian",
		es: "Spanish",
		el: "Greek",
		gu: "Gujarati",
		ht: "Haitian Creole",
		ha: "Hausa",
		haw: "Hawaiian",
		he: "Hebrew",
		hi: "Hindi",
		hmn: "Hmong",
		hu: "Hungarian",
		is: "Icelandic",
		ig: "Igbo",
		id: "Indonesian",
		ga: "Irish",
		it: "Italian",
		ja: "Japanese",
		jv: "Javanese",
		kn: "Kannada",
		kk: "Kazakh",
		km: "Khmer",
		rw: "Kinyarwanda",
		ko: "Korean",
		ku: "Kurdish",
		ky: "Kyrgyz",
		lo: "Lao",
		la: "Latin",
		lv: "Latvian",
		lt: "Lithuanian",
		lb: "Luxembourgish",
		mk: "Macedonian",
		mg: "Malagasy",
		ms: "Malay",
		ml: "Malayalam",
		mt: "Maltese",
		mi: "Maori",
		mr: "Marathi",
		mn: "Mongolian",
		my: "Myanmar (Burmese)",
		ne: "Nepali",
		no: "Norwegian",
		or: "Odia (Oriya)",
		ps: "Pashto",
		fa: "Persian",
		pl: "Polish",
		pt: "Portuguese",
		pa: "Punjabi",
		ro: "Romanian",
		ru: "Russian",
		sm: "Samoan",
		gd: "Scottish Gaelic",
		sr: "Serbian",
		st: "Sesotho",
		sn: "Shona",
		sd: "Sindhi",
		si: "Sinhala",
		sk: "Slovak",
		sl: "Slovenian",
		so: "Somali",
		su: "Sundanese",
		sw: "Swahili",
		sv: "Swedish",
		tg: "Tajik",
		ta: "Tamil",
		tt: "Tatar",
		te: "Telugu",
		th: "Thai",
		tr: "Turkish",
		tk: "Turkmen",
		uk: "Ukrainian",
		ur: "Urdu",
		ug: "Uyghur",
		uz: "Uzbek",
		vi: "Vietnamese",
		cy: "Welsh",
		xh: "Xhosa",
		yi: "Yiddish",
		yo: "Yoruba",
		zu: "Zulu",
	  };	  

  const translateSpokenToSigned = (text: string, spokenLanguage: string, signedLanguage: string) => {
    const api = 'https://us-central1-sign-mt.cloudfunctions.net/spoken_text_to_signed_pose';
    return `${api}?text=${encodeURIComponent(text)}&spoken=${spokenLanguage}&signed=${signedLanguage}`;
  };

  return {
    signedLanguages,
    spokenLanguages,
    translateSpokenToSigned,
  };
};
